apiVersion: v1
kind: Service
metadata:
  name: quintero-bank-front
spec:
  type: LoadBalancer
  selector:
    app: quintero-bank-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
